[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

# SPA redirects - חשוב לאפליקציית React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
